### ISSUE TITLE
Installation with Homebrew

### ISSUE THREAD

**Issue by matricariarecutita** [devwaseem/TempBox#10]
I would like to install the app using [Homebrew](https://brew.sh/). Many Open Source projects are listed there.

**Comment by devwaseem** [comment]
Hi @matricariarecutita. Thanks for checking out the tempbox. I'm planning on making it available on homebrew soon.

**Comment by dec0dOS** [comment]
Hello, @devwaseem! Thanks for the awesome app. I really love it.

Is it possible to manage it via homebrew now?
