### ISSUE TITLE
TempBox.app can’t be opened

### ISSUE THREAD

**Issue by intraector** [devwaseem/TempBox#13]
Hi.
I've installed the app and tried to start it. Here's the message I got:

_“TempBox.app” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information._

**Comment by Kuebic** [comment]
It's a Mac security feature. First time you run it, it won't let you, unless you open the Applications folder in Finder, then specifically right-click > Open, then Open button on the pop-up. Should only happen once per update.

**Comment by intraector** [comment]
Okay, thanks for the quick response
